<?php

/**
 * @file
 * Contains islandora_search_facets.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_search_facets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dragomans search module.
    case 'help.page.islandora_search_facets':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Islandora Search Facets') . '</p>';
      return $output;

    default:
  }
}
